# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dggamma_single_cpp <- function(x, mu, sigma, nu, epsilon, kappa, return_log = TRUE, negate_loglik = FALSE) {
    .Call('_eggamma_dggamma_single_cpp', PACKAGE = 'eggamma', x, mu, sigma, nu, epsilon, kappa, return_log, negate_loglik)
}

dggamma_cpp <- function(x, mu, sigma, nu, epsilon, kappa, return_log = FALSE, negate_loglik = FALSE) {
    .Call('_eggamma_dggamma_cpp', PACKAGE = 'eggamma', x, mu, sigma, nu, epsilon, kappa, return_log, negate_loglik)
}

nllggamma_single_cpp <- function(x, mu, sigma, nu, epsilon, kappa) {
    .Call('_eggamma_nllggamma_single_cpp', PACKAGE = 'eggamma', x, mu, sigma, nu, epsilon, kappa)
}

nllggamma_cpp <- function(x, mu, sigma, nu, weights, epsilon, kappa) {
    .Call('_eggamma_nllggamma_cpp', PACKAGE = 'eggamma', x, mu, sigma, nu, weights, epsilon, kappa)
}

